### PR TITLE
Fix build for ros2 humble

### PR DESCRIPTION
**Pull request by nakai-omer**

### CODE REVIEW

**Review by weeshal — APPROVED** [review]

**Comment by weeshal** [comment]
@ak-nv Can we get an approval on this - rosdep install does not work without the changes to the package.xml files.

**Comment by weeshal** [comment]
Hey one more bump @ak-nv - would benefit greatly from this fix.

**Review by delipl — APPROVED** [review]

**Comment by amilcarlucas** [comment]
Bump, from me too.

**Comment by rbonghi** [comment]
Hi all,

I am working to merge a new release of ros2_jetson_stats on the official branch
https://github.com/rbonghi/ros2_jetson_stats

**Comment by amilcarlucas** [comment]
Very, very nice @rbonghi , I was planning to grab your changes myself and do a upstream PR here :)
Guess I will not need to do that

**Comment by rbonghi** [comment]
I recently had access as a maintainer of this repo.
I will merge when I release the new updates on jetson-stats :-)

PS: the new jetson-stats now works with JP5 and Orin series

**Comment by weeshal** [comment]
Hey @rbonghi do you have any status on when these updates might be merged from your side?

**Comment by rbonghi** [comment]
Hi @weeshal ,

I am thinking to merge temporarily this PR and later (2-3weeks max) merging my fork here.

**Comment by rbonghi** [comment]
Hi, @weeshal. I merged your PR,

I'm still working on rearranging this repo and aligning it with my fork. I need a bit of time, but I will make you free while I use this repo.

**Please note** I changed the `jetson.board` and `jetson.engine` properties (take a look if everything works)

**Pull request merged**
